### ISSUE TITLE
--- stderr: ***-android-gcc: fatal error: no input files

### ISSUE THREAD

**Issue by kogbok** [alexcrichton/openssl-src-rs#13]
Hello

I use hyper with hyper-tls, that use native-tls on ios and android.
On Android, native-tls use openssl-sys, and with the feature: vendored, this crate import openssl-src-rs
my cargo.toml file import native-tls like this. native-tls = { version = "0.2", features = ["vendored"] }

So when I compile on this target:
- i686-linux-android
- arm-linux-androideabi
- aarch64-linux-android

I always have the same error:

```
--- stderr
i686-linux-android-gcc: fatal error: no input files
compilation terminated.
i686-linux-android-ar: creating libssl.a
i686-linux-android-ar: creating libcrypto.a
./libcrypto.a(cryptlib.o):cryptlib.c:function OPENSSL_showfatal: error: undefined reference to 'stderr'
collect2: error: ld returned 1 exit status
./libcrypto.a(cryptlib.o):cryptlib.c:function OPENSSL_showfatal: error: undefined reference to 'stderr'
...
...
```

To avoid this problem, in the crate openssl-src-rs, in the file lib.rs, I add 'no-stdio' option to the perl command: configure.

I have just two questions:
Why don't you need to add this option ? and Is it possible to add this modification to the next release ?

Thanks for considering my request,

**Comment by alexcrichton** [comment]
Oh dear this sounds bad! I think we can definitely pass this option, and I've opened a PR to do so -- https://github.com/alexcrichton/openssl-src-rs/pull/14
