### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by ShootingKing-AM** [alexcrichton/openssl-src-rs#171]
What are these versions ? 300 ? 111 and Cargo.toml has something, cagro update shows someother vesion, github actions generate something else, Crates-io has two version ? Oo ? Can someone clarify this ? (and maybe some readme? Thanks)

**Comment by amousset** [comment]
This probably requires some explanations in the README indeed. There currently two maintained branches:

* `master` which builds OpenSSL 3.0 (with `300.` versions)
* `release/111` which builds OpenSSL 1.1.1 (with `111.*` versions)

`openssl-sys` depends on the `111` versions, so when using a feature flag to statically link openssl from `openssl` or another crate depending on it, you will get a `111` version.

Does this clarify the situation or do you see other inconsistencies?

**Comment by ShootingKing-AM** [comment]
Thanks for the clarification and PR @amousset : )
