### ISSUE TITLE
i686-pc-windows-gnu requires windres too

### ISSUE THREAD

**Issue by pyfqm** [alexcrichton/openssl-src-rs#19]
Cross compiling to i686-pc-windows-gnu requires windres, but [lib.rs](https://github.com/alexcrichton/openssl-src-rs/blob/df07b666e2265ca33138bfb7dfb6f5de258a41e8/src/lib.rs#L232) only checked for x86_64-pc-windows-gnu.

The error message is:
```sh
make[1]: windres: Command not found
```

**Comment by alexcrichton** [comment]
Thanks for the report! Should be a pretty easy fix in theory, would you be willing to send a PR to test it out?
