### ISSUE TITLE
Any plans to cut a release?

### ISSUE THREAD

**Issue by aig787** [alexcrichton/openssl-src-rs#210]
Any plans to cut a release soon? https://github.com/fede1024/rust-rdkafka needs the `force-engine` feature added back in with https://github.com/alexcrichton/openssl-src-rs/commit/26dc3c81d8ebee5f7ec40835e29bf9f37e648ab2 to compile to MUSL.

Thanks!

**Comment by alexcrichton** [comment]
Sure, I'll do that in https://github.com/alexcrichton/openssl-src-rs/pull/211
