### ISSUE TITLE
Allow for the path to the perl installation to be specified

### ISSUE THREAD

**Issue by thomaseizinger** [alexcrichton/openssl-src-rs#45]
Currently, the crate just runs `perl` which will use the first installation that is in the path.

This this not work on the windows-runner of GitHub actions and fails with the following error:

```
error: failed to run custom build command for `openssl-sys v0.9.53`

Caused by:
  process didn't exit successfully: `d:\a\create-comit-app\create-comit-app\target\debug\build\openssl-sys-5ec2b21008c71a01\build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
running "perl" "./Configure" "--prefix=d:\\a\\create-comit-app\\create-comit-app\\target\\debug\\build\\openssl-sys-935999bfd09d3702\\out\\openssl-build\\install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-engine" "no-async" "no-asm" "VC-WIN64A"
Configuring OpenSSL version 1.1.1d (0x1010104fL) for VC-WIN64A
Using os-specific seed configuration

--- stderr

******************************************************************************
This perl implementation doesn't produce Windows like paths (with backward
slash directory separators).  Please use an implementation that matches your
building platform.

This Perl version: 5.26.2 for x86_64-msys-thread-multi
******************************************************************************
```

Adding the already installed version of strawperryperl to the path fixes the issue.

However, it would be nice to have an environment variable that allows one to override the path to the Perl installation. This would make it more obvious, what we need the different Perl installation for.

I am thinking of an env variable like `OPENSSL_SRC_PERL_HOME`.

Thoughts?

**Comment by alexcrichton** [comment]
Sounds reasonable to me to add!

**Comment by sfackler** [comment]
I think `PERL` would be the standard name for the environment variable.

**Comment by thomaseizinger** [comment]
> I think `PERL` would be the standard name for the environment variable.

The idea behind a name like `OPENSSL_SRC_PERL_HOME` or maybe `OPENSSL_SRC_PERL` was to make it explicit that it is openssl that requires this specific perl installation.
In my case, openssl is a transitive dependency, deep down in the dependency tree and the command that I am actually executing is `make release` (which then calls `cargo build` with certain features).

I am not sure how important that actually is though :)

**Comment by Sytten** [comment]
For the sake of other people (including myself) what is the path of the strawberry perl?
@thomaseizinger

**Comment by thomaseizinger** [comment]
@Sytten Last time I used it (3 years ago), it was ` C:/strawberry/perl/bin/perl.exe`.
