### ISSUE TITLE
Bump minor version

### ISSUE THREAD

**Issue by pfmooney** [alexcrichton/openssl-src-rs#57]
In order to be pulled in as a dependency for rust-lang/rust#55553, could you please bump the minor version and publish it?

Thanks for your help.

**Comment by sfackler** [comment]
We need to bump to 1.1.1f anyway, so I'll cut a release tonight.

**Comment by pfmooney** [comment]
> We need to bump to 1.1.1f anyway, so I'll cut a release tonight.

Great! Much appreciated.
