### ISSUE TITLE
AR environment variable is overwritten

### ISSUE THREAD

**Issue by jamesmcm** [alexcrichton/openssl-src-rs#61]
Hi,

This line overwrites the `AR` environment variable if `gcc` has a prefix.

https://github.com/alexcrichton/openssl-src-rs/blob/babdbf06116b22f8fa276da4e25b134d28b54494/src/lib.rs#L222

This is a pain as my `ar` is  `x86_64-unknown-linux-gnu-gcc-ar` not `x86_64-unknown-linux-gnu-ar` - is there any way to override this?

It's running on a build server so I don't have much control.

**Comment by alexcrichton** [comment]
This is likely a bug and something which we should avoid doing if `AR` is already specified.

**Comment by jamesmcm** [comment]
Yeah, in the end I switched the code to use Rustls and it works (though I had a few issues getting the build system to use Clang to compile ring).

**Comment by jamesmcm** [comment]
Addressed in PR #62
