### ISSUE TITLE
Vendored feature failed to cross compile armv7-linux-androideabi 

### ISSUE THREAD

**Issue by songvva** [alexcrichton/openssl-src-rs#71]
Error building OpenSSL:
    Command: "make" "build_libs"
    Exit status: exit code: 2

    ', /home/viga/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.10.2+1.1.1g/src/lib.rs:410:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl-sys v0.9.58`

Caused by:
  process didn't exit successfully: `/home/viga/workspace/test/sidl/target/release/build/openssl-sys-723a9cb19b46db99/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_NO_VENDOR
ARMV7_LINUX_ANDROIDEABI_OPENSSL_NO_VENDOR unset
cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
OPENSSL_NO_VENDOR unset
CC_armv7-linux-androideabi = None
CC_armv7_linux_androideabi = None
TARGET_CC = None
CC = None
CFLAGS_armv7-linux-androideabi = None
CFLAGS_armv7_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = Some("--sysroot=/home/viga/workspace/build_dep/build_sidl/ndk_arm_29/sysroot -I/home/viga/workspace/build_dep/build_sidl/ndk_arm_29/sysroot/usr/include")
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = None
running "perl" "./Configure" "--prefix=/home/viga/workspace/test/sidl/target/armv7-linux-androideabi/release/build/openssl-sys-23571861cd3fdaaf/out/openssl-build/install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-stdio" "no-shared" "linux-armv4" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-mthumb" "-mfpu=vfpv3-d16" "-mfloat-abi=softfp" "--sysroot=/home/viga/workspace/build_dep/build_sidl/ndk_arm_29/sysroot" "-I/home/viga/workspace/build_dep/build_sidl/ndk_arm_29/sysroot/usr/include"
Configuring OpenSSL version 1.1.1g (0x1010107fL) for linux-armv4
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
running "make" "depend"
running "make" "build_libs"
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _build_libs
make[1]: Entering directory `/home/viga/workspace/test/sidl/target/armv7-linux-androideabi/release/build/openssl-sys-23571861cd3fdaaf/out/openssl-build/build/src'
make[1]: Leaving directory `/home/viga/workspace/test/sidl/target/armv7-linux-androideabi/release/build/openssl-sys-23571861cd3fdaaf/out/openssl-build/build/src'
make[1]: Entering directory `/home/viga/workspace/test/sidl/target/armv7-linux-androideabi/release/build/openssl-sys-23571861cd3fdaaf/out/openssl-build/build/src'
CC="arm-linux-androideabi-gcc" /usr/bin/perl crypto/aes/asm/aes-armv4.pl linux32 crypto/aes/aes-armv4.S
............
...........
--- stderr
clang80: error: no input files
crypto/poly1305/poly1305-armv4.S:168:2: error: out of range immediate fixup value
 addeq r12,r11,#(poly1305_emit-.Lpoly1305_init)
 ^
crypto/poly1305/poly1305-armv4.S:169:2: error: out of range immediate fixup value
 addne r12,r11,#(poly1305_emit_neon-.Lpoly1305_init)
 ^
crypto/poly1305/poly1305-armv4.S:171:2: error: out of range immediate fixup value
 addne r11,r11,#(poly1305_blocks_neon-.Lpoly1305_init)
 ^
make[1]: *** [crypto/poly1305/poly1305-armv4.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [build_libs] Error 2
thread 'main' panicked at '

Error building OpenSSL:
    Command: "make" "build_libs"
    Exit status: exit code: 2

    ', /home/viga/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.10.2+1.1.1g/src/lib.rs:410:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Daniihh** [comment]
@songvva mind sharing what you did to fix the problem, if anything?

**Comment by songvva** [comment]
@Daniihh Do you see the same error? We find an alternative rustl.

**Comment by Daniihh** [comment]
Yes, I do, although the code I'm trying to compile depends on multiple dependencies that depend on openssl...
I'm not compiling for arm either, rather x86_64, but same target operating system.
